---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    uses: ./.github/workflows/addon-ci.yaml
    with:
      slug: "zwave-js-ui"
